### ISSUE TITLE
Exception with redefined property(new modifier) stops enrichment altogether

### ISSUE THREAD

**Issue by domagojmedo** [RehanSaeed/Serilog.Exceptions#343] opened 2021-05-14 11:16 UTC
### Describe the feature

Not sure if this eve belongs here, but I'm having trouble getting this package to work with ApplicationInsights sink. I'm trying to get deconstructed Refit.ValidationApiException but no luck.

Any help would be appreciated

**Comment by krajek** [comment] 2021-05-14 11:20
I am using Serilog.Exceptions with ApplicationInsights sink and it works fine.
You need to provide an example `https://stackoverflow.com/help/minimal-reproducible-example`, for us to check.

Moreover, Serilog.Exceptions is basically unrelated to any particular sink, its code its executed before sink code obviously.

**Comment by domagojmedo** [comment] 2021-05-14 11:29
Yea, my bad, it seems that issue is with Refit.ValidationApiException. It's not getting deconstructed. I'll try to create an example

**Comment by domagojmedo** [comment] 2021-05-14 12:52
I'm having trouble finding a public API that will return that exception. 

In this repo everything works when ApiException is caught, but if ValidationApiException is caught then nothing gets deconstructed, not even properties from the base ApiException class. 

I'll try to find a public API that throws ValidationApiException but at the moment this is the best I could come up with

https://github.com/domagojmedo/LoggingExample

**Comment by krajek** [comment] 2021-05-14 13:54
You don't need public API, just create exception manually and verify result in the log output.

**Comment by domagojmedo** [comment] 2021-05-14 14:11
I tried but had issues because it required APiException in constructor. Switched to using reflection now.

Repo is updated, you can see that Content is set to some ProblemDetails object, but nothing is output in console. 
If you uncomment ThrowApiException and comment that method you will see that it works as intended

**Comment by krajek** [comment] 2021-05-14 20:52
Took me a while to understand what is happening and I found out that this particular exception somehow declares property `Content` twice. `Serilog.Exceptions` fails silently in this case so you do not get any enrichment.

![image](https://user-images.githubusercontent.com/3998666/118329249-08162680-b507-11eb-9e78-72ebbd849f4a.png)

I will fix it tomorrow and let you know.

**Comment by krajek** [comment] 2021-05-14 20:54
Ok, it just overrides the definition of `Content` with `new` keyword.

![image](https://user-images.githubusercontent.com/3998666/118329758-59beb100-b507-11eb-8894-c57f7498eb34.png)

**Comment by RehanSaeed** [comment] 2021-05-17 09:04
If someone has used the `new` keyword on a property, they are deliberately hiding the one the base class. I'm not really sure we should we be retrieving both. In this case, the derived class looks like it gives us a better representation of the content (`ProblemDetails`) than the base class (`String`). Thoughts @krajek?

**Comment by krajek** [comment] 2021-05-17 09:50
@RehanSaeed yes, agreed 100%, next PR will tackle that problem.

Just to reiterate: this PR is just a safety mechanism, the last line of defense, but not the only one. 
I assume that robustness(meaning in that case "providing value to the library user" even in the unexpected scenario) is so important for our library that such a mechanism is justifiable.
I will start the next PR just after this is merged.

**Closed** 2021-05-26 08:54 UTC
Labels: enhancement

**Comment by domagojmedo** [comment] 2021-06-14 12:48
@RehanSaeed when can we expect new version with this fix?

**Comment by RehanSaeed** [comment] 2021-06-15 08:12
@krajek Do you want to put in another PR with further improvements? E.g. using `ConcurrentDictionary`?

**Comment by krajek** [comment] 2021-06-15 08:22
Yes, but I would not suggest delaying the release because of that. Other
changes will not affect API.

wt., 15 cze 2021, 10:12 użytkownik Muhammad Rehan Saeed <
***@***.***> napisał:

**Comment by RehanSaeed** [comment] 2021-06-15 09:06
Released in https://github.com/RehanSaeed/Serilog.Exceptions/releases/tag/7.0.0
