### ISSUE TITLE
Question: when following the example from the readme: no extra ExceptionDetails in the log

### ISSUE THREAD

**Issue by arnolddg** [RehanSaeed/Serilog.Exceptions#12] opened 2016-11-08 10:47 UTC
The example as explained in Readme.md is not working for me, no extra information is shown.
I made a little testprogram (see attached [TestSeri.zip](https://github.com/RehanSaeed/Serilog.Exceptions/files/577904/TestSeri.zip)), using serilog v2.3 and Serilog.Exceptions v2.2.1 (installed via NuGet) and EntityFramework 6.1.3.
In that program I use the following structure taken from the Readme.md:
`try
{
    ...
}
catch (DbEntityValidationException exception)
{
    logger.Error(exception, "Hello World");
}`

But I see no additional information, for example

`{
	"Timestamp": "2016-11-08T10:21:32.0619281+01:00",
	"Level": "Error",
	"MessageTemplate": "Hello World",
	"RenderedMessage": "Hello World",
	"Exception": "System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.\r\n   at System.Data.Entity.Internal.InternalContext.SaveChanges()\r\n   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()\r\n   at System.Data.Entity.DbContext.SaveChanges()\r\n   at TestSeri.Program.Main(String[] args) in C:\\Users\\arnold.de.groot\\Documents\\Visual Studio 2015\\Projects\\TestSeri\\TestSeri\\Program.cs:line 34"
}`

As a workaround, I do now:
`try
{
    ...
}
catch (DbEntityValidationException exception)
{
    logger.Error(exception, "Hello World {@exception}", exception);
}`

and then the RenderedMessage contains the expected 
destructured exception details.
What's wrong?

**Comment by arnolddg** [comment] 2016-11-08 11:41
Added note:
after enabling debugging with
`Serilog.Debugging.SelfLog.Enable(msg => System.Diagnostics.Debug.WriteLine(msg));`

it appears that under the hood an exception is thrown, System.Reflection.TargetParameterCountException: Parameter count mismatch.
[Serilog-debugging-exception.txt](https://github.com/RehanSaeed/Serilog.Exceptions/files/578025/Serilog-debugging-exception.txt)

**Comment by RehanSaeed** [comment] 2017-01-07 18:47
I suppose this is a duplicate of https://github.com/RehanSaeed/Serilog.Exceptions/issues/13? Re-open if I'm wrong.

**Closed by RehanSaeed** 2017-01-07 18:47 UTC
