### ISSUE TITLE
TypeLoadException w/ Mono 4.2.3

### ISSUE THREAD

**Issue by MattAlex151** [RehanSaeed/Serilog.Exceptions#2] opened 2016-04-14 20:25 UTC
I'm trying to use Serilog.Exceptions 1.1.0 with Serilog 1.5.14 and Mono 4.2.3 but every time I try to run .Enrich.WithExceptionDetails using either the .NET 4.0 or 4.5 dlls (matching Serilog and Serilog.Exceptions of course) I'm getting a TypeLoadException. 

Here is a stack trace: 

```
   SetUp : System.TypeLoadException : Could not resolve type with token 01000058
  at Serilog.Exceptions.Destructurers.ExceptionEnricher..ctor (IEnumerable`1 destructurers) <0x41a1fe80 + 0x000e4> in <filename unknown>:0 
  at Serilog.Exceptions.Destructurers.ExceptionEnricher..ctor (Serilog.Exceptions.Destructurers.IExceptionDestructurer[] destructurers) <0x41a1fe50 + 0x00013> in <filename unknown>:0 
  at Serilog.Exceptions.Destructurers.ExceptionEnricher..ctor () <0x41a1fe10 + 0x0001f> in <filename unknown>:0 
  at Serilog.Exceptions.LoggerEnrichmentConfigurationExtensions.WithExceptionDetails (Serilog.Configuration.LoggerEnrichmentConfiguration loggerEnrichmentConfiguration) <0x41a1fb60 + 0x0005b> in <filename unknown>:0 
  at MyApp.InitializeGlobalLogger () <0x41a1a5d0 + 0x0014b> in <filename unknown>:0 
  at SetUpFixture..ctor () <0x41a1a580 + 0x0000b> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x4183a250 + 0x00045> in <filename unknown>:0 
```

and some version info:
```
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

If Serilog.Exceptions uses P/Invokes then that is certainly the issue as these are not supported by Mono. Thanks for taking a look, and let me know if I can provide more information.

**Comment by RehanSaeed** [comment] 2016-04-15 12:00
Thanks for posting this. There is no P/Invoke in Serilog.Exceptions.

Probably this is caused by [`ExceptionDestructurer`](https://github.com/RehanSaeed/Serilog.Exceptions/blob/master/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs) because it contains a list of all the exceptions with just the default `Exception` properties. One of the `Exception` types in that long list may not be supported on Mono?

Unfortunately, the exception you posted does not list which type is causing the problem. If you would like to test this, you can grab the Serilog.Exceptions project and try debugging it directly, rather than using the NuGet package.

**Comment by MattAlex151** [comment] 2016-04-15 18:36
Hey thanks! I'm trying to compile from source on Linux, and I'm running in to some issues there too. I have to run now so I figured I'd post my progress to see if it shed some more light. First, I had:

`/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Serilog.Exceptions.xproj: error : /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Serilog.Exceptions.xproj: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Serilog.Exceptions.xproj could not import "$(VSToolsPath)\DNX\Microsoft.DNX.Props"
`

So I found the following post: https://github.com/travis-ci/travis-ci/issues/5164 and followed the instructions here: https://github.com/travis-ci/travis-ci/issues/5164#issuecomment-160680779

So now I try to build your project.json file, with the following result:

`Microsoft .NET Development Utility Mono-x64-1.0.0-rc1-16609


Building . for .NETFramework,Version=v4.0
  Using Project dependency . 1.1.0
    Source: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json

  Using Package dependency Serilog 1.5.14
    Source: /home/matt/.dnx/packages/Serilog/1.5.14
    File: lib/net40/Serilog.dll
    File: lib/net40/Serilog.FullNetFx.dll

  Using Assembly dependency fx/System 4.0.0
    Source: /usr/lib/mono/4.0/System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: /usr/lib/mono/4.0/System.Core.dll

  Using Assembly dependency fx/System.Data 4.0.0
    Source: /usr/lib/mono/4.0/System.Data.dll

  Unable to resolve dependency fx/System.Runtime 

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: /usr/lib/mono/4.0/mscorlib.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: /usr/lib/mono/4.0/Microsoft.CSharp.dll

/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(28,27): error NU1001: The dependency fx/System.Runtime  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(56,51): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(57,51): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(58,51): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(59,51): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(85,39): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(86,39): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(87,39): .NETFramework,Version=v4.0 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)

Building . for .NETFramework,Version=v4.5
  Using Project dependency . 1.1.0
    Source: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json

  Using Package dependency Serilog 1.5.14
    Source: /home/matt/.dnx/packages/Serilog/1.5.14
    File: lib/net45/Serilog.dll
    File: lib/net45/Serilog.FullNetFx.dll

  Using Assembly dependency fx/System 4.0.0
    Source: /usr/lib/mono/4.5/System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: /usr/lib/mono/4.5/System.Core.dll

  Using Assembly dependency fx/System.Data 4.0.0
    Source: /usr/lib/mono/4.5/System.Data.dll

  Using Assembly dependency fx/System.Runtime 4.0.0
    Source: /usr/lib/mono/4.5/Facades/System.Runtime.dll

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: /usr/lib/mono/4.5/mscorlib.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: /usr/lib/mono/4.5/Microsoft.CSharp.dll

/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(56,51): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(57,51): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(58,51): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(59,51): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(61,59): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'EventSourceException' does not exist in the namespace 'System.Diagnostics.Tracing' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(85,39): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(86,39): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(87,39): .NETFramework,Version=v4.5 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/SqlExceptionDestructurer.cs(24,42): .NETFramework,Version=v4.5 error CS0117: 'SqlException' does not contain a definition for 'ClientConnectionId'
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/SqlExceptionDestructurer.cs(24,76): .NETFramework,Version=v4.5 error CS1061: 'SqlException' does not contain a definition for 'ClientConnectionId' and no extension method 'ClientConnectionId' accepting a first argument of type 'SqlException' could be found (are you missing a using directive or an assembly reference?)

Building . for .NETFramework,Version=v4.5.1
  Using Project dependency . 1.1.0
    Source: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json

  Using Package dependency Serilog 1.5.14
    Source: /home/matt/.dnx/packages/Serilog/1.5.14
    File: lib/net45/Serilog.dll
    File: lib/net45/Serilog.FullNetFx.dll

  Using Assembly dependency fx/System 4.0.0
    Source: /usr/lib/mono/4.5/System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: /usr/lib/mono/4.5/System.Core.dll

  Using Assembly dependency fx/System.Data 4.0.0
    Source: /usr/lib/mono/4.5/System.Data.dll

  Using Assembly dependency fx/System.Runtime 4.0.0
    Source: /usr/lib/mono/4.5/Facades/System.Runtime.dll

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: /usr/lib/mono/4.5/mscorlib.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: /usr/lib/mono/4.5/Microsoft.CSharp.dll

/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(56,51): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(57,51): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(58,51): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(59,51): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(61,59): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'EventSourceException' does not exist in the namespace 'System.Diagnostics.Tracing' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(85,39): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(86,39): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs(87,39): .NETFramework,Version=v4.5.1 error CS0234: The type or namespace name 'Management' does not exist in the namespace 'System' (are you missing an assembly reference?)
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/SqlExceptionDestructurer.cs(24,42): .NETFramework,Version=v4.5.1 error CS0117: 'SqlException' does not contain a definition for 'ClientConnectionId'
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/Destructurers/SqlExceptionDestructurer.cs(24,76): .NETFramework,Version=v4.5.1 error CS1061: 'SqlException' does not contain a definition for 'ClientConnectionId' and no extension method 'ClientConnectionId' accepting a first argument of type 'SqlException' could be found (are you missing a using directive or an assembly reference?)

Building . for .NETFramework,Version=v4.5.2
  Using Project dependency . 1.1.0
    Source: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json

  Using Package dependency Serilog 1.5.14
    Source: /home/matt/.dnx/packages/Serilog/1.5.14
    File: lib/net45/Serilog.dll
    File: lib/net45/Serilog.FullNetFx.dll

  Unable to resolve dependency fx/System 

  Unable to resolve dependency fx/System.Core 

  Unable to resolve dependency fx/System.Data 

  Unable to resolve dependency fx/System.Runtime 

  Unable to resolve dependency fx/mscorlib 

  Unable to resolve dependency fx/Microsoft.CSharp 

/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/System  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/System.Core  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(60,24): error NU1001: The dependency fx/System.Data  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(61,27): error NU1001: The dependency fx/System.Runtime  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/mscorlib  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/Microsoft.CSharp  could not be resolved.
error CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.

Building . for .NETFramework,Version=v4.6
  Using Project dependency . 1.1.0
    Source: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json

  Using Package dependency Serilog 1.5.14
    Source: /home/matt/.dnx/packages/Serilog/1.5.14
    File: lib/net45/Serilog.dll
    File: lib/net45/Serilog.FullNetFx.dll

  Unable to resolve dependency fx/System 

  Unable to resolve dependency fx/System.Core 

  Unable to resolve dependency fx/System.Data 

  Unable to resolve dependency fx/System.Runtime 

  Unable to resolve dependency fx/mscorlib 

  Unable to resolve dependency fx/Microsoft.CSharp 

/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/System  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/System.Core  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(71,24): error NU1001: The dependency fx/System.Data  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(72,27): error NU1001: The dependency fx/System.Runtime  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/mscorlib  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/Microsoft.CSharp  could not be resolved.
error CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.

Building . for .NETFramework,Version=v4.6.1
  Using Project dependency . 1.1.0
    Source: /home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json

  Using Package dependency Serilog 1.5.14
    Source: /home/matt/.dnx/packages/Serilog/1.5.14
    File: lib/net45/Serilog.dll
    File: lib/net45/Serilog.FullNetFx.dll

  Unable to resolve dependency fx/System 

  Unable to resolve dependency fx/System.Core 

  Unable to resolve dependency fx/System.Data 

  Unable to resolve dependency fx/System.Runtime 

  Unable to resolve dependency fx/mscorlib 

  Unable to resolve dependency fx/Microsoft.CSharp 

/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/System  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/System.Core  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(82,24): error NU1001: The dependency fx/System.Data  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(83,27): error NU1001: The dependency fx/System.Runtime  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/mscorlib  could not be resolved.
/home/matt/serilog/Serilog.Exceptions/Source/Serilog.Exceptions/project.json(0,0): error NU1001: The dependency fx/Microsoft.CSharp  could not be resolved.
error CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.

Build failed.
    0 Warning(s)
    49 Error(s)

Time elapsed 00:00:01.8116590
Total build time elapsed: 00:00:01.8360651
Total projects built: 1
`

**Comment by RehanSaeed** [comment] 2016-06-17 14:24
Feel free to reopen if you need me to do anything.

**Comment by laedit** [comment] 2016-08-28 17:43
So after some search it seems that the following exceptions [can't be loaded on Mono](https://travis-ci.org/laedit/Serilog.Exceptions.Tests/builds/155761054):

 - System.Diagnostics.Eventing.Reader.EventLogInvalidDataException
 - System.Diagnostics.Eventing.Reader.EventLogNotFoundException
 - System.Diagnostics.Eventing.Reader.EventLogProviderDisabledException
 - System.Diagnostics.Eventing.Reader.EventLogReadingException
 - System.Management.Instrumentation.InstanceNotFoundException
 - System.Management.Instrumentation.InstrumentationBaseException
 - System.Management.Instrumentation.InstrumentationException

They are all from `System.Core` which I think is in Mono 4.0, but I think that these types [aren't part of Mono for now](https://travis-ci.org/laedit/Serilog.Exceptions.Tests/builds/155764204).

Is it possible to exclude them on Mono?

**Comment by RehanSaeed** [comment] 2016-08-30 09:33
I'm not sure. Presumably we could use a pre-processor directive but I'm not sure how to do this in the new project.json world. Any ideas?

**Comment by laedit** [comment] 2016-08-30 12:09
I am not sure this is possible.
But following the [netstandard mapping to platforms](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md), if you add another target to `netstandard1.2` mono should be covered.

**Comment by RehanSaeed** [comment] 2016-08-30 13:13
Have you tested that? Would you be willing to submit a PR for the above?

**Comment by laedit** [comment] 2016-08-30 13:22
I haven't, I am not at all familiar with `netstandard`.

**Comment by laedit** [comment] 2016-08-30 21:03
So I've tried but ended with nothing, this was a dead-end: `System.Core` isn't supported by any `netstandard` targets.
And after some though I don't think having a `mono` target can help: for example my application target .NET 4.5, which is supposed to be largely compatible with mono, so when the build is fetching the nuget `Serilog.Exceptions` package, it's the `net45` which is referenced no matter what.

So I think that the only solutions until Mono supports these types are modification in applications/libraries wich reference `Serilog.Exceptions`:
 - define a `MONO` pre-processor directive which exclude the call to `Enrich.WithExceptions()`.
 - override the destructurers and not include the `ExceptionDestructurer`, but define a new one which includes only types compatible with all platforms.

Sorry for the bothering.

**Comment by laedit** [comment] 2016-08-31 04:35
Thanks to http://apisof.net I can confirm that these types are only available in the [full .NET Framework]'(https://apisof.net/catalog/System.Diagnostics.Eventing.Reader.EventLogInvalidDataException).

**Comment by RehanSaeed** [comment] 2016-08-31 08:02
Perhaps we could check if these types exist in the assemblies and only add them if they do?

**Comment by laedit** [comment] 2016-08-31 09:05
Excellent idea! :smile: 
I was so focused on pre-processor directive that I haven't think of that.

**Comment by RehanSaeed** [comment] 2016-09-10 11:07
@laedit  So I created a Travis build [here](https://travis-ci.org/RehanSaeed/Serilog.Exceptions/jobs/158945843) but it's failing. The errors suggest that there are other types not supported on Mono. Is this correct?

**Comment by laedit** [comment] 2016-09-10 12:35
Strange, the 'EventSourceException' should have fail my test.
Apisof.net confirm that it doesn't exists on Mono.
I will look into it tomorrow, I can't do it right now.

**Comment by RehanSaeed** [comment] 2016-09-10 18:06
Cool, looks like it was worth investing in Travis CI.

**Comment by laedit** [comment] 2016-09-11 05:54
Yes, that was an excellent idea 😄 

I have tested the use of the new version of `Serilog.Exceptions` on a Travis build and [it passed](https://travis-ci.org/laedit/Serilog.Exceptions.Tests/builds/159072786).
The difference is that I always install the latest version of mono and in your config you specified the version `4.2.3`.

So if you want to support that specific version, I will add `EventSourceException` and `SqlException` to the types not handled by mono.

**Comment by RehanSaeed** [comment] 2016-09-11 09:23
I just tried 4.4.2 [here](https://travis-ci.org/RehanSaeed/Serilog.Exceptions/builds/159085840) and according to [this](http://www.mono-project.com/docs/about-mono/releases/) thats the latest release version.

**Comment by laedit** [comment] 2016-09-11 13:50
Ok, so I honestly don't know why it is working on my test project.
Nevertheless, I will test all types with apisof.net to see if there are other that I missed.

**Comment by RehanSaeed** [comment] 2016-10-13 07:39
The ground has shifted again.

netstandard 2.0 will add support for Mono. If we target that, then Mono support will be assured and we won't have to do reflection in `SqlExceptionDestructurer`. I say we wait for official Mono support.

Also, by then xproj to csproj will be complete, and the Tooling bug stopping our Travis CI builds from successfully running xUnit tests on Mono will be fixed.

**Closed by RehanSaeed** 2016-10-13 07:39 UTC
Labels: bug
